### ISSUE TITLE
还是没有接口文档吗

### ISSUE THREAD

**Issue by Xiaofufufu** [abcd498936590/Dart-Cms#4]
如果有接口文档，我也想写一个App来用

**Comment by abcd498936590** [comment]
没有，不过你可以参考我的flutter案例，我写了一个flutter的电影app，接入我的这个cms作为安卓端。在cms的 router/app可以找到app端的接口。可以观察下，然后数据库里面字段稍微研究下就ok了。
最近我会再优化一版，结果一下ejs，换成art模板引擎试下速度。

**Comment by abcd498936590** [comment]
> 如果有接口文档，我也想写一个App来用

没有，不过你可以参考我的flutter案例，我写了一个flutter的电影app，接收我的这个cms作为安卓端。在cms的router / app可以找到app端的接口。可以观察下，然后数据库里面平行稍微研究下就ok了。
最近我会再优化一版，结果一下ejs，换成art模板引擎试下速度。
